# Generated by Django 4.2.1 on 2023-11-20 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askmeApp', '0002_instancetype_profile_tag_remove_answer_public_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancetype',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerInstance', to='askmeApp.answer'),
        ),
        migrations.AlterField(
            model_name='instancetype',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionInstance', to='askmeApp.question'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_type',
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='askmeApp.profile'),
        ),
        migrations.RemoveField(
            model_name='repost',
            name='repost_type',
        ),
        migrations.AlterField(
            model_name='repost',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repost', to='askmeApp.profile'),
        ),
        migrations.AddField(
            model_name='like',
            name='like_type',
            field=models.ManyToManyField(related_name='likes', to='askmeApp.instancetype'),
        ),
        migrations.AddField(
            model_name='repost',
            name='repost_type',
            field=models.ManyToManyField(related_name='reposts', to='askmeApp.instancetype'),
        ),
    ]
